### ISSUE TITLE
mmdetection

### ISSUE THREAD

**Issue by thestars-maker** [wefantasy/label-studio-demo#1]
请问mmdetection已经训练了一个模型权重，现在需要将其对一个文件夹所有数据集进行打标签并标注伪框，保存XML文件，请问应该怎样配置相关文件呢？
/backend/mmdetection/model/fcos_common.py应该对应的是mmdetection那个文件呢

**Comment by wefantasy** [comment]
> 请问mmdetection已经训练了一个模型权重，现在需要将其对一个文件夹所有数据集进行打标签并标注伪框，保存XML文件，请问应该怎样配置相关文件呢？ /backend/mmdetection/model/fcos_common.py应该对应的是mmdetection那个文件呢

@thestars-maker 先在labelstudio的web页面中创建一个对应项目，并将需要标注的数据集上传至该项目；然后仿造[后端配置](https://ifantasy.net/2022/07/27/label_studio_setup_and_auto_label/#%E5%90%8E%E7%AB%AF%E9%85%8D%E7%BD%AE)中的示例，调用已训练好的mmdetection模型进行数据标记（主要是predict方法）并且启动后端服务，这一步需要大量测试很难快速完成；最后在web页面的该项目中接入定制的后端模型，不出意外的话刷新后里面的数据集就会被自动标注了。

**Comment by thestars-maker** [comment]
对于这种自动标注的数据集可以将其转化为VOC格式嘛，可以保存检测框位置的XML嘛，如果可以的话，需要怎么操作呢

**Comment by wefantasy** [comment]
> 存检测框位置的XML嘛

@thestars-maker 应该是可以的，在web页面项目那里有个标注数据导出的功能，可以选择导出的标注格式，然后可以用第三方程序将标注数据转为所需格式。
